name: NYTimes Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.TRIGGER_WORKFLOW }}

      - name: Generate file
        run: |
          pip install requests
          python scraper.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: update daily puzzles"
